Update proxy.rb
Previous version:
 - `./proxy.rb:204:in `block in parse': undefined method `define_options' for #<ProcessScriptArguments::ScriptOptions:0x01e7f758> (NoMethodError)`

Removed unused parameter from method